language: ruby
dist: precise
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
install:
  - bundle install
  - gem build swapus.gemspec
  - gem install swapus-$(cat VERSION).gem
script:
  - rubocop
  - swapus
  - swapus -v | grep $(cat VERSION)
